### ISSUE TITLE
circuit-breaker not working on oauth2 plugin paths

### ISSUE THREAD

**Issue by vigohe** [dream11/kong-circuit-breaker#19]
### Summary

`kong-circuit-breaker` does not work along OAuth2 kong plugin. Paths where OAuth2 it`s set, `kong-circuit-breaker` `api_call_timeout_ms` does not apply

### Steps To Reproduce

1. Install OAuth2 plugin at a service
2. Install kong-circuit-breaker plugin

### Additional Details & Logs

- Kong version `Kong Enterprise 2.7.0.0`

**Comment by chirag-manwani** [comment]
@vigohe Could you provide the config for Oauth2 Plugin you are using?

**Comment by vigohe** [comment]
kong-plugin-enterprise-oauth2-introspection 0.5.3-0

config:

```
            "config": {
                "pkce": "lax",
                "token_expiration": 1,
                "refresh_token_ttl": 1,
                "global_credentials": true,
                "persistent_refresh_token": false,
                "reuse_refresh_token": false,
                "accept_http_if_already_terminated": false,
                "provision_key": "xxxxxxxxxxxxx",
                "enable_client_credentials": false,
                "enable_authorization_code": false,
                "enable_implicit_grant": false,
                "mandatory_scope": false,
                "auth_header_name": "authorization",
                "anonymous": null,
                "hide_credentials": false,
                "enable_password_grant": true,
                "scopes": null
            }
```

**Comment by chirag-manwani** [comment]
@vigohe Could you check this once https://github.com/dream11/kong-circuit-breaker/issues/21#issuecomment-1049509892 and update if you are still facing the same issue.
