### ISSUE TITLE
why doesn't it work?

### ISSUE THREAD

**Issue by quanzzkk** [dream11/kong-circuit-breaker#20]
![image](https://user-images.githubusercontent.com/93415688/153329488-ec92d1dc-3cf0-4675-97c4-0f417082ff9a.png)

**Comment by chirag-manwani** [comment]
Could you provide some more details like Kong version, Plugin version, Kong error logs?

**Comment by quanzzkk** [comment]
kong version 1.3.0, plguin version 1.0.0，，sorry, where can I find the error logs?

**Comment by quanzzkk** [comment]
I had solve this problem by  changing "kong.core_cache" to "kong.cache" at helpers.lua:10. but now I meet the "The upstream server is timing out" too

**Comment by chirag-manwani** [comment]
@quanzzkk Thank you for pointing this out, we can fix this(kong.core_cache -> kong.cache) in the next release.
Also, could you check once if the upstream server is actually timing out?
Timeout is an HTTP client attribute and has nothing to do with Circuit breaker (or even Kong). You can set the timeout value (in ms) using this plugin or you could use the Service level setting to set the timeout.

**Comment by chirag-manwani** [comment]
@quanzzkk This issue cannot be fixed as Kong now uses kong.core_cache to store all entities. The plugin listens to invalidation events on this cache. So to support Kong 1.X we would need to add logic per Kong version (add listeners to kong.cache in case of Kong 1.x) which is overkill. 
Closing this issue as we do not plan to support Kong 1.x.
